// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHxivUoYcItBGwLxaKJwDuHCibzrJ9QM',
    appId: '1:876546834844:web:2a10b9097220152b980859',
    messagingSenderId: '876546834844',
    projectId: 'cipherxexpensetracker-bec90',
    authDomain: 'cipherxexpensetracker-bec90.firebaseapp.com',
    storageBucket: 'cipherxexpensetracker-bec90.firebasestorage.app',
    measurementId: 'G-ZPQ8WHPZ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTr4Bgl-6th2QoF9hNihnWuwQJ7A3UFxA',
    appId: '1:876546834844:android:a73f24abd72e6c5d980859',
    messagingSenderId: '876546834844',
    projectId: 'cipherxexpensetracker-bec90',
    storageBucket: 'cipherxexpensetracker-bec90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMEkWUscmmatvLmQfi_KYc3MSHLwptE68',
    appId: '1:876546834844:ios:d1bd5ffb7f6eee07980859',
    messagingSenderId: '876546834844',
    projectId: 'cipherxexpensetracker-bec90',
    storageBucket: 'cipherxexpensetracker-bec90.firebasestorage.app',
    iosBundleId: 'com.example.expenseAppUsingBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMEkWUscmmatvLmQfi_KYc3MSHLwptE68',
    appId: '1:876546834844:ios:d1bd5ffb7f6eee07980859',
    messagingSenderId: '876546834844',
    projectId: 'cipherxexpensetracker-bec90',
    storageBucket: 'cipherxexpensetracker-bec90.firebasestorage.app',
    iosBundleId: 'com.example.expenseAppUsingBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZHxivUoYcItBGwLxaKJwDuHCibzrJ9QM',
    appId: '1:876546834844:web:c04e3b8fa8dc1756980859',
    messagingSenderId: '876546834844',
    projectId: 'cipherxexpensetracker-bec90',
    authDomain: 'cipherxexpensetracker-bec90.firebaseapp.com',
    storageBucket: 'cipherxexpensetracker-bec90.firebasestorage.app',
    measurementId: 'G-7HGPBQ35LV',
  );
}
